In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('C:/Users/vaibh/Downloads/covid_toy.csv')
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [7]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

with out column transform ------------ aam jindagi  

In [13]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [14]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=.3)

In [18]:
x_train

age  gender  fever   cough       city
40   49  Female  102.0    Mild      Delhi
13   64    Male  102.0    Mild  Bangalore
5    84  Female    NaN    Mild  Bangalore
67   65    Male   99.0    Mild  Bangalore
50   19    Male  101.0    Mild      Delhi
..  ...     ...    ...     ...        ...
95   12  Female  104.0    Mild  Bangalore
76   80    Male  100.0    Mild  Bangalore
41   82    Male    NaN    Mild    Kolkata
94   79    Male    NaN  Strong    Kolkata
11   65  Female   98.0    Mild     Mumbai

[70 rows x 5 columns]

In [25]:
si=SimpleImputer()
x_train_fever=si.fit_transform(x_train[['fever']])

x_test_fever=si.fit_transform(x_test[['fever']])

In [26]:
x_train_fever

array([[102.        ],
       [102.        ],
       [100.71428571],
       [ 99.        ],
       [101.        ],
       [101.        ],
       [ 98.        ],
       [103.        ],
       [100.        ],
       [100.        ],
       [104.        ],
       [ 98.        ],
       [100.71428571],
       [ 99.        ],
       [102.        ],
       [103.        ],
       [100.71428571],
       [101.        ],
       [104.        ],
       [ 98.        ],
       [101.        ],
       [ 99.        ],
       [100.        ],
       [100.71428571],
       [100.        ],
       [101.        ],
       [ 99.        ],
       [104.        ],
       [ 98.        ],
       [100.        ],
       [101.        ],
       [104.        ],
       [ 98.        ],
       [101.        ],
       [101.        ],
       [ 98.        ],
       [ 98.        ],
       [103.        ],
       [103.        ],
       [ 99.        ],
       [102.        ],
       [103.        ],
       [100.        ],
       [ 98

In [28]:
x_train_fever.shape

(70, 1)

In [29]:
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [32]:
oe=OrdinalEncoder(categories=[['Mild','Strong']])

x_train_cough=oe.fit_transform(x_train[['cough']])
x_test_cough=oe.fit_transform(x_test[['cough']])

In [33]:
x_train_cough

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.]])

In [35]:
x_train_cough.shape

(70, 1)

In [36]:
# one_hot ecnoding <>gender city

In [40]:
ohe=OneHotEncoder(drop='first',sparse_output=False)

x_train_gender_city=ohe.fit_transform(x_train[['gender','city']])

x_test_gender_city=ohe.fit_transform(x_test[['gender','city']])


In [41]:
x_train_gender_city

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],


In [42]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [43]:
x_train_gender_city.shape

(70, 4)

In [44]:
# extracting age 

In [51]:
x_train_age=x_train.drop(columns=['gender','fever','cough','city']).values

# also the test the data  

x_test_age=x_test.drop(columns=['gender','fever','cough','city']).values

In [54]:
x_train_age.shape

(70, 1)

In [55]:
# concatenate 

In [58]:
x_train_transformed=np.concatenate((x_train_age,x_train_cough,x_train_fever,x_train_gender_city),axis=1)
x_train_transformed

array([[ 49.        ,   0.        , 102.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 64.        ,   0.        , 102.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 84.        ,   0.        , 100.71428571,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 65.        ,   0.        ,  99.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 19.        ,   0.        , 101.        ,   1.        ,
          1.        ,   0.        ,   0.        ],
       [ 47.        ,   1.        , 101.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 10.        ,   1.        ,  98.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 70.        ,   1.        , 103.        ,   1.        ,
          0.        ,   1.        ,   0.        ],
       [ 19.        ,   1.        , 100.        ,   0.        ,
          0.    

In [60]:
x_test_transformed=np.concatenate((x_test_age,x_test_cough,x_test_cough,x_test_gender_city),axis=1)

In [61]:
x_test_transformed

array([[33.,  1.,  1.,  0.,  1.,  0.,  0.],
       [31.,  0.,  0.,  0.,  0.,  1.,  0.],
       [60.,  0.,  0.,  1.,  0.,  1.,  0.],
       [51.,  1.,  1.,  0.,  0.,  1.,  0.],
       [74.,  0.,  0.,  1.,  0.,  0.,  1.],
       [83.,  0.,  0.,  1.,  1.,  0.,  0.],
       [34.,  1.,  1.,  0.,  1.,  0.,  0.],
       [42.,  1.,  1.,  0.,  0.,  0.,  0.],
       [16.,  0.,  0.,  0.,  0.,  0.,  0.],
       [18.,  0.,  0.,  0.,  0.,  0.,  0.],
       [65.,  0.,  0.,  1.,  1.,  0.,  0.],
       [69.,  0.,  0.,  0.,  0.,  0.,  0.],
       [26.,  0.,  0.,  0.,  0.,  1.,  0.],
       [44.,  0.,  0.,  1.,  0.,  0.,  1.],
       [11.,  1.,  1.,  0.,  0.,  1.,  0.],
       [14.,  1.,  1.,  1.,  0.,  0.,  0.],
       [42.,  0.,  0.,  1.,  1.,  0.,  0.],
       [69.,  0.,  0.,  0.,  0.,  1.,  0.],
       [75.,  0.,  0.,  0.,  1.,  0.,  0.],
       [38.,  0.,  0.,  0.,  0.,  0.,  0.],
       [24.,  0.,  0.,  1.,  0.,  1.,  0.],
       [ 8.,  0.,  0.,  0.,  0.,  1.,  0.],
       [20.,  0.,  0.,  0.,  0.,

In [62]:
x_train_transformed.shape

(70, 7)

In [63]:
# using column transform  ........... mentos jindagi

In [64]:
from sklearn.compose import ColumnTransformer


In [74]:
transformer=ColumnTransformer(transformers=[
    
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False, drop='first'),['gender','city'])
    
    
    
    
    
    ],remainder='passthrough')

In [75]:
transformer.fit_transform(x_train)

array([[102.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  49.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  64.        ],
       [100.71428571,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  84.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  65.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  19.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  47.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  10.        ],
       [103.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  70.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.    

In [76]:
transformer.fit_transform(x_train).shape

(70, 7)

In [77]:
transformer.fit_transform(x_test)

array([[102.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  33.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  31.        ],
       [103.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  60.        ],
       [101.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  51.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  74.        ],
       [ 98.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  83.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  34.        ],
       [101.14814815,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  42.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          0.    

In [78]:
transformer.fit_transform(x_test).shape

(30, 7)