In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('C:/Users/vaibh/Downloads/titanic_toy.csv')

df.head()

Age     Fare  Family  Survived
0  22.0   7.2500       1         0
1  38.0  71.2833       1         1
2  26.0   7.9250       0         1
3  35.0  53.1000       1         1
4  35.0   8.0500       0         0

In [5]:
df.shape

(891, 4)

In [7]:
df.isnull().mean()

Age         0.198653
Fare        0.050505
Family      0.000000
Survived    0.000000
dtype: float64

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [13]:
x=df.drop(columns=['Survived'])
y=df.iloc[:,-1]

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.3,random_state=41)

In [19]:
imputer1=SimpleImputer(strategy='mean')
imputer2=SimpleImputer(strategy='median')

In [23]:
trf=ColumnTransformer([
    
    
    
    ('mean_age',imputer1,[0]),
    ('median_age',imputer2,[1])
],remainder='passthrough')

In [24]:
trf

ColumnTransformer(remainder='passthrough',
                  transformers=[('mean_age', SimpleImputer(), [0]),
                                ('median_age', SimpleImputer(), [1])])

In [41]:
trf.fit(x_train)

ColumnTransformer(remainder='passthrough',
                  transformers=[('mean_age', SimpleImputer(), [0]),
                                ('median_age', SimpleImputer(), [1])])

In [42]:
trf.named_transformers_['mean_age'].statistics_

array([29.30416499])

In [43]:
trf.named_transformers_['median_age'].statistics_

array([31.12506293])

In [44]:
trf.fit_transform(x_train)
trf.fit_transform(x_test)

array([[ 30.60368664,   8.05      ,   0.        ],
       [ 21.        ,  16.1       ,   0.        ],
       [ 30.        , 106.425     ,   0.        ],
       [ 25.        ,  41.5792    ,   3.        ],
       [ 31.        ,   7.8542    ,   0.        ],
       [ 27.        ,  26.        ,   0.        ],
       [ 22.        ,  34.9100124 ,   0.        ],
       [ 33.        ,  86.5       ,   0.        ],
       [ 31.        ,   8.6833    ,   0.        ],
       [ 60.        ,  75.25      ,   1.        ],
       [ 45.        ,  26.55      ,   0.        ],
       [ 30.60368664,   7.75      ,   0.        ],
       [ 37.        ,  52.5542    ,   2.        ],
       [ 41.        ,  19.5       ,   1.        ],
       [ 21.        , 262.375     ,   4.        ],
       [ 18.        ,  73.5       ,   0.        ],
       [ 19.        ,  13.        ,   0.        ],
       [ 19.        ,   7.8958    ,   0.        ],
       [ 23.        ,   7.8542    ,   0.        ],
       [ 30.60368664,   8.05   